### PR TITLE
feat: create ecommerce azurite queue automatically

### PR DESCRIPTION
**Pull request by pietro-tota**
Add script to create azurite ecommerce queues.

Queue names are taken from env files taking all parameters which value start with `pagopa-ecommerce` and ends with `-queue`.

### CODE REVIEW

**Comment by giovanniberti** [comment]
I think the approach is a little bit heavyweight, wouldn't a shell script with a few `az storage queue create ...` be sufficient?

**Comment by pietro-tota** [comment]
> I can’t see the env file with all the queue names. Maybe you need to archive it? Still great job🙂

It reads variables from copied env files (see docker file)

**Comment by pietro-tota** [comment]
> I think the approach is a little bit heavyweight, wouldn't a shell script with a few `az storage queue create ...` be sufficient?

Yes, I first started with this approach but then I think that this module can be in future be used to initialize all other resources such as mongo collections and so on and that having a java runtime can be easier to perform all other initializations programmatically.
But sure all of this can be done also with scripts too

**Review by giovanniberti — APPROVED** [review]

**Review by giovanniberti — CHANGES_REQUESTED** [review]
Can you add an invocation with a service when using docker compose?

**Comment by pietro-tota** [comment]
> Can you add an invocation with a service when using docker compose?



> Can you add an invocation with a service when using docker compose?

Add `azurite init container` with https://github.com/pagopa/pagopa-ecommerce-local/pull/64/commits/33d3f968b03ffbfb4b0c870e8bb508f4e6f3705a

**Review by giovanniberti — COMMENTED** [review]
Good job! Just a few trivial issues :)

**Review by giovanniberti — APPROVED** [review]

**Pull request merged**
